# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

xcodeproj 'NumberKeyboardViewDemo.xcodeproj'

target 'NumberKeyboardViewDemo' do
  pod 'CYRKeyboardButton'
end

target 'NumberKeyboardViewDemoTests' do

end

