//
//  YZKeyboardStyle.swift
//  NumberKeyboardViewDemo
//
//  Created by Yichi Zhang on 15/03/2015.
//  Copyright (c) 2015 Yichi Zhang. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class YZKeyboardStyle : NSObject {

    //// Drawing Methods

    public class func drawArrowLight() {

        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(1, 2))
        bezier2Path.addLineToPoint(CGPointMake(9, 2))
        bezier2Path.addLineToPoint(CGPointMake(5, 6))
        bezier2Path.addLineToPoint(CGPointMake(1, 2))
        bezier2Path.closePath()
        UIColor.whiteColor().setFill()
        bezier2Path.fill()
    }

    public class func drawArrowDark() {
        //// Color Declarations
        let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(1, 2))
        bezier2Path.addLineToPoint(CGPointMake(9, 2))
        bezier2Path.addLineToPoint(CGPointMake(5, 6))
        bezier2Path.addLineToPoint(CGPointMake(1, 2))
        bezier2Path.closePath()
        color.setFill()
        bezier2Path.fill()
    }

    //// Generated Images

    public class var imageOfArrowLight: UIImage {
		
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 8), false, 0)
            YZKeyboardStyle.drawArrowLight()

        let imageOfArrowLight = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfArrowLight
    }

    public class var imageOfArrowDark: UIImage {
		
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 8), false, 0)
            YZKeyboardStyle.drawArrowDark()

        let imageOfArrowDark = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfArrowDark
    }

}