//
//  YZKeyboardStyle.swift
//  NumberKeyboardViewDemo
//
//  Created by Yichi Zhang on 15/03/2015.
//  Copyright (c) 2015 Yichi Zhang. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class YZKeyboardStyle : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfArrowLight: UIImage?
        static var arrowLightTargets: [AnyObject]?
        static var imageOfArrowDark: UIImage?
        static var arrowDarkTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawArrowLight() {

        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(1, 2))
        bezier2Path.addLineToPoint(CGPointMake(9, 2))
        bezier2Path.addLineToPoint(CGPointMake(5, 6))
        bezier2Path.addLineToPoint(CGPointMake(1, 2))
        bezier2Path.closePath()
        UIColor.whiteColor().setFill()
        bezier2Path.fill()
    }

    public class func drawArrowDark() {
        //// Color Declarations
        let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(1, 2))
        bezier2Path.addLineToPoint(CGPointMake(9, 2))
        bezier2Path.addLineToPoint(CGPointMake(5, 6))
        bezier2Path.addLineToPoint(CGPointMake(1, 2))
        bezier2Path.closePath()
        color.setFill()
        bezier2Path.fill()
    }

    //// Generated Images

    public class var imageOfArrowLight: UIImage {
        if Cache.imageOfArrowLight != nil {
            return Cache.imageOfArrowLight!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 8), false, 0)
            YZKeyboardStyle.drawArrowLight()

        Cache.imageOfArrowLight = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfArrowLight!
    }

    public class var imageOfArrowDark: UIImage {
        if Cache.imageOfArrowDark != nil {
            return Cache.imageOfArrowDark!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 8), false, 0)
            YZKeyboardStyle.drawArrowDark()

        Cache.imageOfArrowDark = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfArrowDark!
    }

    //// Customization Infrastructure

    @IBOutlet var arrowLightTargets: [AnyObject]! {
        get { return Cache.arrowLightTargets }
        set {
            Cache.arrowLightTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(YZKeyboardStyle.imageOfArrowLight)
            }
        }
    }

    @IBOutlet var arrowDarkTargets: [AnyObject]! {
        get { return Cache.arrowDarkTargets }
        set {
            Cache.arrowDarkTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(YZKeyboardStyle.imageOfArrowDark)
            }
        }
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
